version: "3.1"

services:
  db:
    image: mysql:8.0.40
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sql_test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    container_name: goback_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - goback_redis:/var/lib/goback_redis
    # command: ["redis-server", "--appendonly", "yes"] # 启动 redis 并开启 AOF 持久化
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  goback_redis:
